version: 0.0

os: linux 
files:
  - source: /
    destination: /home/ec2-user

hooks:

# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 1300
      runas: ec2-user
