version: 0.2
phases:
  pre_build:
    commands:
      - apt update -y
      - apt install nodejs -y
      - apt install libssl-dev -y
      - apt install npm -y
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

