name: Sonar Cloud - Branch Analysis
on: 
   push:
   pull_request:
    branches: 
      - "*"
   # A workflow run is made up of one or more jobs that can run sequentially or in parallel   
jobs:
  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  
    - name: install npm
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'
    - name: build project
      run: |
        projectname=`git show --format="" --name-only | xargs dirname | sort | uniq`
        echo "projectname=$projectname" >> $GITHUB_ENV
        echo $projectname
        aws configure
        
    
     #   curl -v -X POST https://3e59557e76bb1e832212a641cb88b09db5f69413@sonarcloud.io/api/projects/create -d "name=$projectname&project=$projectname&organization=harishsingh2707"   
  #  - name: Analyze with SonarCloud
   #   uses: sonarsource/sonarcloud-github-action@master
    #  with:
     #   projectBaseDir: ${{ env.projectname }}
     #   args: >
     #     -Dsonar.organization=harishsingh2707
      #    -Dsonar.projectKey=${{ env.projectname }}
      #env:
       #   GITHUB_TOKEN: "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"
        #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
      
      

