name: Sonar Cloud - Branch Analysis
on: 
   push:
   pull_request:
    branches: 
      - "*"
   # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Node install dependencies
      run: |
        #sudo apt update -y
        #sudo apt install nodejs -y
        #sudo apt install libssl-dev -y
        #sudo apt install npm -y
        projectname=`git show --format="" --name-only | xargs dirname | sort | uniq`
        echo $projectname
        curl -v -X POST https://3e59557e76bb1e832212a641cb88b09db5f69413@sonarcloud.io/api/projects/create -d "name=$projectname&project=$projectname&organization=harishsingh2707"
        #sudo npm install -g eslint
        #eslint --init
        #npm test run -- --code-coverage --no-watch --no-progress --browsers ChromeHeadlessNoSandbox
    - name: pass the variable value
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        projectname=`git show --format="" --name-only | xargs dirname | sort | uniq`
        echo "projectname=$projectname" >> $GITHUB_ENV
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ${{ env.projectname }}
        args: >
          -Dsonar.organization=harishsingh2707
          -Dsonar.projectKey=${{ env.projectname }}
      env:
          GITHUB_TOKEN: "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"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
      
      

