name: Sonar Cloud - Branch Analysis
on: 
   push:
   pull_request:
    branches: 
      - "*"
   # A workflow run is made up of one or more jobs that can run sequentially or in parallel   
jobs:
  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        
    - name: build project
      run: |
        projectname=`git show --format="" --name-only | xargs dirname | sort | uniq`
        echo "projectname=$projectname" >> $GITHUB_ENV
        echo $projectname
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
        aws-region: us-east-1

     #   curl -v -X POST https://3e59557e76bb1e832212a641cb88b09db5f69413@sonarcloud.io/api/projects/create -d "name=$projectname&project=$projectname&organization=harishsingh2707"   
  #  - name: Analyze with SonarCloud
   #   uses: sonarsource/sonarcloud-github-action@master
    #  with:
     #   projectBaseDir: ${{ env.projectname }}
     #   args: >
     #     -Dsonar.organization=harishsingh2707
      #    -Dsonar.projectKey=${{ env.projectname }}
      #env:
       #   GITHUB_TOKEN: "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"
        #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
      
      

